<a href="https://colab.research.google.com/github/Arghay013/machine-learning-start/blob/main/numpy/data_analysis_with_numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

arr = np.random.randint(1 ,100 , size =(10,5)) # sample - 10 , feature - 5

In [12]:
arr.shape

(10, 5)

In [13]:
b = arr.reshape(5,10)

# b.shape
# b.ndim
b

array([[12, 10, 66, 52, 19, 53, 42, 73, 19, 78],
       [21, 99, 88, 17, 41, 47, 66, 98, 71,  1],
       [60, 73, 53, 60, 82, 67, 72, 15, 59,  1],
       [98, 73, 73, 87, 76, 30, 34, 26, 73, 23],
       [33, 49, 77,  1, 22, 80, 64, 68,  9, 57]])

In [14]:
flatten = b.flatten()
print(flatten.ndim)
flatten

column_wise_flattening = np.ravel(b,order= 'C')

print(column_wise_flattening)

1
[12 10 66 52 19 53 42 73 19 78 21 99 88 17 41 47 66 98 71  1 60 73 53 60
 82 67 72 15 59  1 98 73 73 87 76 30 34 26 73 23 33 49 77  1 22 80 64 68
  9 57]


#### reshape die 1 dimentional theke multidimentional kore
#### flatten and ravel die one dimentional kore


In [15]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3))

### concatinate

In [16]:
con_row = np.concatenate((a,b),axis=0) # row wise

print(con_row)

con_col = np.concatenate((a,b), axis = 1) # column wise

print(con_col)

[[ 4  8  9]
 [ 6  7  9]
 [23 27 28]
 [21 25 21]]
[[ 4  8  9 23 27 28]
 [ 6  7  9 21 25 21]]


In [17]:
# error

# row wise concetanate korar shomoi column same thakbe
# col wise concat korar shomoi row ta same thakte hobe

x = np.random.randint(1 ,10 , size =(2,3))
y = np.random.randint(1 ,10 , size =(1,3))

r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x,y),axis =1 )
print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### transpose

In [18]:
# transpose

mat = np.array([[10,20,30],
                [30,40,50]
               ])


transpose = mat.T

print(transpose)

[[10 30]
 [20 40]
 [30 50]]


### array split

In [19]:
a = np.random.randint(1 ,9 , size =(10,))
print(a)
splitted_array = np.array_split(a,3)

print(splitted_array)

# split -> equal division
splitted_array = np.split(a,3)

[1 8 7 1 5 5 3 2 2 2]
[array([1, 8, 7, 1]), array([5, 5, 3]), array([2, 2, 2])]


ValueError: array split does not result in an equal division

## arithmetic operator and mathematical functions

In [20]:
# faster for vectorization

x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ])

add = np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x % y

print(remainder)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


# mathematical function

In [21]:
 # trigonometry

# sin , cos , tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

# deg2rad

[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [22]:
#log

x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x)
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [23]:
# different
s = np.sum(x)
print(s)

#prefix sum
cumul =np.cumulative_sum(x)
print(cumul)

134


AttributeError: module 'numpy' has no attribute 'cumulative_sum'

In [24]:
#broadcasting

x = np.array([ 10 , 8 , 16 , 100 ])

result = x + 2

#rulings = columns er size and vector er size same hote hobe

matrix = np.array([[10,20,30],
                [30,40,50]
               ])


result = matrix + 2

vector = np.array([1,2,3,4])

result = matrix +vector
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

## Logical Function

In [25]:
# comparison - >,< , >= ,<= , == , !=

x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ])

greater_than = x>y

print(greater_than)

equal = x==y

print(equal)

# all () -> shob true kina
# any() -> jekono ekta true ase kina

print(np.all(greater_than))

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


## Sorting

In [26]:
#inplace
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z)

z.sort()

print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [27]:
# copy sorting
print(x)
sort_arr = np.sort(x)

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [28]:
# 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Searching

In [29]:
print(x)

[ 10   8  16 100]


In [30]:
# np.where( condition , x , y ) if true x , otherwise replace with y

index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [31]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [32]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [35]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x)
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


## counting in ndarray

In [36]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[74 56 83 27 43 85 49 85 27 13 96 94 89 87 46 62 15 40 94 29 11 62 69 77
 58 56 43 44 39 63 55 63 33 22 65 39 70 76 53 28 84 70 77 77 10  6 72 69
 49 63 48 76 67 12  7 35 88 67 15 31 48 12 19  3 94 34 51 42 92 32 54 49
 25  9 19 46  6 87 55 15 57 84 46 26 52 54 83 49 81  3 51 94 11  3 43 71
 48 82 83 71]


In [39]:
value_great_than_60 = np.count_nonzero(a>=77)
print(value_great_than_60)

22


In [46]:
unique_value,count = np.unique(a, return_counts=True)
print(unique_value)
print(count)

[ 3  6  7  9 10 11 12 13 15 19 22 25 26 27 28 29 31 32 33 34 35 39 40 42
 43 44 46 48 49 51 52 53 54 55 56 57 58 62 63 65 67 69 70 71 72 74 76 77
 81 82 83 84 85 87 88 89 92 94 96]
[3 2 1 1 1 2 2 1 3 2 1 1 1 2 1 1 1 1 1 1 1 2 1 1 3 1 3 3 4 2 1 1 2 2 2 1 1
 2 3 1 2 2 2 2 1 1 2 3 1 1 3 2 2 2 1 1 1 4 1]


# statistical function

In [50]:
# data load
data = np.genfromtxt('student_marks.csv', delimiter=',',skip_header=1, usecols=(1,2,3))
print(data)

[[85. 89. 82.]
 [90. 84. 88.]
 [78. 80. 90.]
 [92. 91. 85.]
 [88. 85. 86.]
 [80. 79. 84.]
 [76. 88. 79.]
 [95. 92. 91.]
 [83. 86. 87.]
 [89. 83. 83.]
 [91. 90. 92.]
 [74. 75. 80.]
 [86. 87. 88.]
 [88. 89. 85.]
 [77. 81. 81.]
 [93. 93. 90.]
 [84. 78. 84.]
 [81. 82. 86.]
 [79. 88. 78.]
 [87. 85. 89.]]


In [58]:
eng_marks = data[:,1:2]
print(eng_marks.T)
max_eng_marks = np.max(eng_marks)
print(max_eng_marks)

min_eng_marks = np.min(eng_marks)
print(min_eng_marks)

average_eng_marks = np.mean(eng_marks)
print(average_eng_marks)

median_eng_marks = np.median(eng_marks)
print(median_eng_marks)

# standard deviation

std_eng_marks = np.std(eng_marks)
print(std_eng_marks)

[[89. 84. 80. 91. 85. 79. 88. 92. 86. 83. 90. 75. 87. 89. 81. 93. 78. 82.
  88. 85.]]
93.0
75.0
85.25
85.5
4.836062447901185


In [59]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


## linear algebra

In [60]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)


# trace
print(np.trace(B))


#

[[ 58  64]
 [139 154]]
17


In [61]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

0.0
2


In [62]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
